version: "3.7"

services:
  db:
    container_name: Postgres
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=library    

  node:
    container_name: Nodeapp
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - db
    volumes:
      - .:/app
      
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8081:8082"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--prefix=/jenkins
    restart: always
    user: root


